### ISSUE TITLE
Cross-origin requests include Backend Authorization header

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#101]
In Central, we use an `axios` instance that exclusively sends requests to Backend. When the user logs in, we update that Backend `axios` instance so that all its requests include an `Authorization` header.

However, due to an `axios` bug, the `Authorization` header is being included with *all* `axios` requests, not just the ones through the Backend `axios` instance. (See [here](https://github.com/axios/axios/issues/1522).) This means that requests to servers other than Backend will include the Central `Authorization` header.

We don't have any cross-origin requests at the moment, but we should keep this issue in mind if/when we add any. It looks like `axios` has fixed the bug, it just hasn't gone out in a release yet. Hopefully there's a new release soon. If not, another option might be for us to update our `request` mixin.

**Comment by fqborges** [comment]
As a workaround, when you create an instance passing the deep object hierarchy it works as expected.

```js
const apiAxios = axios.create({
  headers: {
    common: {},
  },
});
```
