### ISSUE TITLE
When no horizontal scrolling is needed, white bar shows in place of scroll bar

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/central-frontend#129]
Chrome 68.0.3440.106, macOS 10.13.4.

See the white bar at the bottom when all questions fit horizontally:
<img width="1895" alt="screen shot 2018-08-30 at 11 00 33 am" src="https://user-images.githubusercontent.com/967540/44870095-11baab80-ac44-11e8-8bcc-ab1eb15d7111.png">

When the window width is reduced, the scroll bar appears as expected: 
<img width="757" alt="screen shot 2018-08-30 at 11 06 08 am" src="https://user-images.githubusercontent.com/967540/44870341-d9679d00-ac44-11e8-8db7-06ab9f8da8bb.png">

**Comment by clint-tseng** [comment]
To clarify, this bug will only surface if you are crazy like LN or I and use a mac but manually went to system preferences and set scrollbars to "always display".

**Comment by lognaturel** [comment]
🤔 :think: I definitely don't remember doing that! Would be good to get another check on a Mac. If it is only a thing that happens under very specific conditions then I agree we can close.

Apologies, I couldn't find a record of our prior conversation about this.

**Comment by lognaturel** [comment]
My settings:
<img width="415" alt="screen shot 2018-08-30 at 11 47 15 am" src="https://user-images.githubusercontent.com/967540/44872471-7973f500-ac4a-11e8-97f9-4e02d1a45230.png">

**Comment by clint-tseng** [comment]
Interesting. I think the default (which eg Matt has) is "When scrolling". This "Automatically" thing is new, I'm not sure how it works.

**Comment by clint-tseng** [comment]
(And in either case, when you last pointed this out my main problem was that the bar appeared in a nonsensical spot; now that it appears just below the table attached to it I don't really have a problem with this visual artifact at all personally)

**Comment by lognaturel** [comment]
> I think the default (which eg Matt has) is "When scrolling". 

That's right, I remember, now. And the slight challenge with that is that a user needs to know about gestures.

Since it's platform and settings specific, I'm going to close. At least I'll have a record of the conversation next time I get puzzled by it.

I also think removing the gradient will help because then it won't be so high contrast.
