### ISSUE TITLE
Dropdown menus are misaligned

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#139]
Dropdown menus are slightly misaligned with the edge of the buttons that open them, in two places:

**The navbar**

<img width="186" alt="navbar" src="https://user-images.githubusercontent.com/5970131/45117450-a5e4b100-b123-11e8-8083-66510fdac970.png">

**The web users list**

<img width="385" alt="user_list" src="https://user-images.githubusercontent.com/5970131/45117456-ad0bbf00-b123-11e8-87db-8495584bfcac.png">

Dropdown menus are correctly aligned in the app users list, so we should be able to borrow some of that page's styles to resolve this issue.

**Comment by matthew-white** [comment]
@clint-tseng, @lognaturel, just to check, how troubling do you find this misalignment? I can also close this issue if it's not worth trying to adjust these.

**Comment by lognaturel** [comment]
I would never have noticed this but now that I see it's different between the two user types, I can't unsee it! It does seem like that style should be reused between the two.

The navbar one doesn't bother me. It looks aligned with the down arrow.

**Comment by lognaturel** [comment]
> update the app users list so that it matches the navbar and web users list

That works for me.
