### ISSUE TITLE
HTML entities in submissions table should be displayed decoded

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/central-frontend#151]
<img width="379" alt="screen shot 2018-09-18 at 12 06 31 pm" src="https://user-images.githubusercontent.com/967540/45710384-564ab000-bb3b-11e8-8b86-dad6d5b991e7.png">

Should say Fooé.

This points to a broader issue that also touches the backend because CSVs and data served through OData will also include HTML-encoded characters. Submissions from Collect encode non-ASCII characters. 

Aggregate and Briefcase decodes these upon display or export ~decodes these upon saving the submission so everything after that is UTF-8~. That's what users are used to and I do think it makes more sense. Can/should the server do that conversion? Would there be a big performance hit in doing the conversion for each node value? Perhaps we should also explore if it's possible for Collect to send UTF-8 encoded submissions without breaking things downstream?

CC @clint-tseng

**Comment by clint-tseng** [comment]
Hm. It's surprising to me that Collect sends HTML entities. I don't like the idea of messing with the submission data at all on its way in. How hard would it be to have Collect send UTF-8?

**Comment by lognaturel** [comment]
I hadn't noticed that's how non-ASCII characters were represented until now. Agreed with not messing with data on its way in. Aggregate and Briefcase actually do it on the way out. Do you have a sense of what the performance hit would be for the OData feed and CSV export?

> How hard would it be to have Collect send UTF-8?

Not hard from an implementation standpoint but we'd have to be careful to understand the implications. It might cause a lot of problems for systems that receive submissions.

**Comment by clint-tseng** [comment]
I'm less concerned about performance hit, though surely there would be some, as I am worried about just messing with the data in general. HTML entities are not exactly the most precise way to encode characters; there's a strong reason they are losing favor (apart from the XML char escape sequences) to plain UTF-8.

**Comment by matthew-white** [comment]
This may be too much complexity on the Collect side, but could HTML entities vs. UTF-8 be a Collect setting that defaults to HTML entities? If that setting is then settable by QR code, then maybe we could have Central set it via app user QR code?

**Comment by lognaturel** [comment]
@MartijnR, how does Enketo represent non-ASCII characters in submissions? That is, does it include an [`encoding` declaration](https://www.w3.org/TR/2008/REC-xml-20081126/#charencoding) and/or does it escape the characters? Apologies, I don't have a quick way to verify this at the moment!

Regardless, I think consumers of submissions should be able to handle escaped characters and present them meaningfully to users because [they are part of XML](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-notation) (see the very first expression).

> HTML entities are not exactly the most precise way to encode characters

I may have been imprecise in my language. You mean using entity **names** is problematic, right? Entity numbers [are ISO 10646](https://www.w3.org/TR/html4/charset.html#h-5.3.1) so I don't think there are any precision issues in this context. Again, they're part of XML.

> could HTML entities vs. UTF-8 be a Collect setting that defaults to HTML entities

I think this is too confusing for users and shouldn't be necessary.

**Comment by MartijnR** [comment]
Enketo doesn't do anything special, except out-of-the box browser-built-in serializing with [XMLSerializer](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer/serializeToString). It doesn't even specify encoding in the submission.

This is part of a submission with &:
<img width="201" alt="screen shot 2018-09-24 at 4 45 17 pm" src="https://user-images.githubusercontent.com/627350/45983430-c19ff080-c019-11e8-80bb-9621623ac0dc.png">

**Comment by lognaturel** [comment]
Thanks, @MartijnR! Interesting that it uses an entity name there. If the value given for a text field is "😴", is that serialized as 😴or &#128564; or something else?

**Comment by MartijnR** [comment]
I am seeing this:

<img width="617" alt="screen shot 2018-09-24 at 5 18 29 pm" src="https://user-images.githubusercontent.com/627350/45984379-17769780-c01e-11e8-9116-7bb3a6067db7.png">

<img width="539" alt="screen shot 2018-09-24 at 5 19 09 pm" src="https://user-images.githubusercontent.com/627350/45984385-1b0a1e80-c01e-11e8-91f7-4d11ff94c15e.png">

**Comment by lognaturel** [comment]
Thanks. So it looks like it will populate the submission with unicode. The declaration is probably `<?xml version="1.0" encoding="UTF-8">`.

**Comment by lognaturel** [comment]
@clint-tseng I think this will be handled on the backend so this issue can be closed, is that right?

**Comment by matthew-white** [comment]
My sense from our discussion is that any changes for this would be implemented in Backend. I've created a [new Backend issue](https://github.com/opendatakit/central-backend/issues/136) and will go ahead and close this issue, but we can always reopen this Frontend issue if that'd be useful.
