### ISSUE TITLE
On password reset/account claim failure, suggest expired link as possibility

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/central-frontend#155]
Right now if an expired link is used, it just fails with a generic authorization failed error. We should amend the message to suggest the possibility that the link has expired and a new email should be sent.

**Comment by lognaturel** [comment]
What's the expiration time? Is it perhaps too aggressive or do you think it matches norms?

**Comment by clint-tseng** [comment]
Right now it's 24 hours. I think 24 and 72 are the standard numbers. I don't have a problem with making it 72.

**Comment by lognaturel** [comment]
24 hours seems great. [Here](https://forum.opendatakit.org/t/error-with-new-account-creation-odk-central/15599/4) we have "Link didn't work within 5 minutes of receiving it" so it seems something else might have gone wrong?

**Comment by matthew-white** [comment]
I think it may still be an open question why the link seemed not to work within 5 minutes of its receipt, but for now, how about I update the error message shown in Frontend, and if we hear about the issue again, we can continue investigating then?

**Comment by matthew-white** [comment]
Resolved by #169.
