### ISSUE TITLE
Don't load submissions in chunks if there are relatively few

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#161]
Once #159 is merged, submissions will load in the form submissions table as follows:

* Only the first 250 load at first.
* When the user scrolls to the bottom of the table, more submissions load.
* The first three times that the user loads more rows, they get 250 more rows each time.
* After that, they get 1000 more rows each time.

However, we want to change this so that if there are relatively few submissions in total (300 or less), they all load at once, rather than in chunks.

**Comment by matthew-white** [comment]
@issa-tseng, would you be comfortable with this issue being closed? I feel like this issue targets a relatively specific case (when a form has 251–300 submissions). I feel like the submissions page is already complex enough that it probably isn't worth it to add extra logic around this case.

**Comment by issa-tseng** [comment]
dunno. @lognaturel thoughts on whether we should miser this bandwidth/request count?

**Comment by lognaturel** [comment]
I would tend to close. Seems like a minor optimization to me.

**Comment by matthew-white** [comment]
Sounds good — I'll go ahead and close.
