### ISSUE TITLE
Requesting submissions for a form that has no submissions

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#168]
Before Central requests a form's submissions for the submissions page, it already knows how many submissions the form has (or at least how many it had at one point). That's because we request that information for the form overview, as extended metadata. However, right now, even if the form has no submissions, Central will still request its submissions for the submissions page. During the request, it displays the message, "Loading 0 submissions..."

I think at the least, we should update the message to read, "Loading submissions..." (or something along those lines).

We might also consider simply not requesting submissions in that case. However, I'd worry that that logic might not be transparent to the user. For example, if a user navigates to the form overview and sees that the form has no submissions, they might wait a while before navigating to the submissions page. If the submissions page then says "There are no submissions", the user might interpret that as an up-to-date status, even if Frontend did not send a new request to confirm that there are no submissions.

**Comment by clint-tseng** [comment]
i think i'm going to revisit this case when we merge the submissions table onto the form index page? probably? so it's possible in this case the table won't even be present. i think i wouldn't worry too much about this for now.

**Comment by matthew-white** [comment]
@lognaturel and I were discussing this case the other day while reviewing #197. I think we're not going to change the current behavior for now, but I have fixed the loading message so that it says "Loading submissions&hellip;" rather than "Loading 0 submissions&hellip;". I'll go ahead and close this issue for now.
