### ISSUE TITLE
Position navbar absolutely

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#172]
Especially since alerts are positioned absolutely near the top of the page, I think it could be good to position the navbar absolutely as well. That way, as the user scrolls down the page, the navbar will remain visible at the top of the page. If an alert is visible, the navbar will not scroll even as the alert remains positioned absolutely, as happens now.

**Comment by matthew-white** [comment]
I feel less sure about this change, and also don't feel as strongly that it's important. If there are no objections, I think I'll go ahead and close this issue.

**Comment by issa-tseng** [comment]
yeah meh
