### ISSUE TITLE
Do not display form id if it is the same as form name

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#179]
Right now in the form list, if a form has a name/title, we display both its id and its name. If a form does not have a name, we display only its id. However, that means that right now, if a form has a name, and its name is the same as its id, we display the same thing twice. Instead, in that case, we should display it only once.

**Comment by clint-tseng** [comment]
eh. i don’t know if i agree with this necessarily. and eventually i’d like to demote the form id as a user-facing piece of information in general. and in the meantime i don’t like having a lot of different display cases. if i’m a user i’m going to wonder why the form id is missing from these forms, for example.

**Comment by matthew-white** [comment]
I think I saw a separate conversation elsewhere about how we might display the form id and version differently than we do now. Given that that's up in the air, it sounds like it might make sense to close this issue for now.
