### ISSUE TITLE
Add display name to user list

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#180]
Now that a user's display name can be updated more easily, it is less likely to be the same as the user's email address. Right now in the user list, we include a column for email address, but not one for display name. @clint-tseng, what do you think about adding a column for display name?

**Comment by clint-tseng** [comment]
yeah we should do this but we can do it as a later pass with an actual story, not an issue ticket.

in general i feel like issue tickets should be reserved for fixes etc.. i don’t like tracking items in multiple locations. things that add value should be tracked as stories. or else we end up with value being tracked here and in the spreadsheet and nobody knows where to look for what, and then we end up just giving up on tracking things.

**Comment by matthew-white** [comment]
I'm open to whatever process makes sense! I agree that completely new functionality should originate from the spreadsheet and release criteria. It feels slightly less clear to me when it's a change to existing functionality.

If the change is sizable, I would again tend to think that it should originate from the spreadsheet. But if it's small enough, it seems like it sometimes works well for it to be a GitHub issue. GitHub issues are easy to create, and they facilitate discussion. When there are open issues, it's easy to select from them when there's time between releases, and they can also be labeled as "help wanted". We seem to have a number of issues in Frontend and Backend that are oriented around enhancing or updating existing functionality rather than fixing bugs, and it does feel like there's a use for those.

Definitely it feels like a bit of a fine line though. There may be a gray zone in which it's not clear whether a change is best tracked in GitHub vs. the spreadsheet. Here are questions that to me feel like they would help determine where a change is best tracked.

* Is the change completely new functionality? (If so, it should likely go in the spreadsheet.)
* Is the change a sizable change to existing functionality? (If so, it should likely go in the spreadsheet.)
* Does the change depend on ongoing or future work? (If it's not possible to implement it soon, it should likely go in the spreadsheet.)
* Is the change a bug fix or implementation detail? (If so, it should go in GitHub.)
* Is the change a small style change or another small change to existing functionality? (If so, it might work well in GitHub.)
* Is it not clear that we want the change, or would the change otherwise benefit from discussion now? (If so, it might work best for it to at least start out in GitHub.)
* Is the change something we are open to contributors working on? (If so, it should go in GitHub.)

I also realized that I had been thinking of the spreadsheet as something relatively fixed, but it seems like it's more dynamic than I realized. What's the best way to add a new issue to the spreadsheet? If I come across a new issue that belongs in the spreadsheet, should I add it as a new row and assign it a number? Or is there a better process?

**Comment by clint-tseng** [comment]
yeah the spreadsheet absolutely changes; the whole purpose of an agile-like
process is adaptation and incremental change. i have been thinking about
this and i think i’ll start a separate document with sort of nascent/small
ideas and we can agglomerate them into proper stories as we go.

as for criteria, the one and only question is typically: “does this add
user value?” if it is a fix that restores what should have already been
user value, the answer is no. if it’s a technical item that the user does
not care about, the answer is no. the answer to all other things is yes.
“implementation detail” is a really difficult categorization to make. so is
“small change.”

the one tough spot is contributors. i don’t have a great response to this
yet. but we’ll come up with one when we have contributors.

**Comment by matthew-white** [comment]
Done in #210.
