### ISSUE TITLE
Insufficient dev setup instructions

### ISSUE THREAD

**Issue by magicznyleszek** [opendatakit/central-frontend#188]
I was able to run ODK Central BE and FE locally for development purposes. I went to [localhost:8989](localhost:8989) and saw this:

<img width="332" alt="screenshot 2019-01-08 at 13 13 52" src="https://user-images.githubusercontent.com/2521888/50830210-6df6b000-1347-11e9-8415-d2318aa85d75.png">

I don't recall setting any email+password user anywhere. Is there a default one?

**Comment by matthew-white** [comment]
Hello @magicznyleszek! No default user is created when you set up Central: you need to create one. You can find more information about that in the section about command line scripts in the Backend readme. There are a couple of commands you can use to create a user, then promote that user to an administrator.

By the way, on a separate note, until #187 is merged (which should be soon), the `master` branches of Frontend and Backend are slightly out of sync. For now, you might want to check out the commits for the latest release.

**Comment by matthew-white** [comment]
As an update, #187 is now merged, so the `master` branches of Frontend and Backend are now in sync. The `master` branch represents our progress toward the upcoming [0.4.0](https://github.com/opendatakit/central/issues/34) release. We still have a few stories to implement for that release, but you can also check out the commits for the 0.3.0 release if you prefer to see things in a less intermediate state. Either way, let us know if anything else arises as you get set up.

**Comment by matthew-white** [comment]
We've released our latest version, [v0.4 Beta](https://forum.opendatakit.org/t/odk-central-v0-4-beta/16857)! I'm going to go ahead and close this issue, but feel free to open a new one if anything else arises as you get set up.
