### ISSUE TITLE
The media table is sometimes empty after refresh

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/central-frontend#269]
Discovered along with https://github.com/opendatakit/central-backend/issues/243

Sometimes, when I refresh the media file page, the table is empty:
<img width="590" alt="Screen Shot 2019-12-12 at 9 33 58 AM" src="https://user-images.githubusercontent.com/967540/70735199-93f8a300-1cc2-11ea-8068-0530ead52330.png">

There's no particular pattern. Sometimes I refresh and I see the media file and sometimes it's gone. All of my forms with media seem to have this property.

Chrome Version 78.0.3904.108 (Official Build) (64-bit)

versions:
75f11f18b6d697a73b025b46a9d0e7f6e2e5f0c0
U0000000000000000000000000000000000000000 client
+63ecaece46a52fd0e8cf4a0f64b2d189660e149b server (v0.6.0-beta.0-54-g63ecaec)

**Comment by matthew-white** [comment]
This should be resolved by #270!

**Comment by lognaturel** [comment]
<img src="https://media.giphy.com/media/2vq7nD921FOBt9Htps/source.gif" />
