### ISSUE TITLE
Deployment weight too heavy

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/central-frontend#37]
The final JS bundle is 3.0MB, which is absolutely gargantuan. The bootstrap CSS is 112KB, which is more palatable but still seems highly excessive for a bunch of CSS. We should aim to bring these down by orders of magnitude by release.

**Comment by matthew-white** [comment]
I thought I'd comment with the latest numbers. After `npm run build`, `build.js` is 417KB. With #44 merged, `build.css` is now 104KB (90KB Bootstrap / 14KB other). Are those sizes low enough for now, or is there more we should try to do before release?

**Comment by clint-tseng** [comment]
those are still quite large; is there anything you can do to bring the js file down especially?

**Comment by matthew-white** [comment]
I took a look at our dependencies, which seem to account for most of the size of the `.js` file:

| Name | Minified size (KB) |
| :- | :- |
| `jquery` | 85.1 |
| `vue` | 60.1 |
| `vue-router` | 23.9 |
| `moment` | 50.4 |
| `pako` (to compress the QR code) | 27.3 |
| `qrcode-generator` | 18.5 |
| `axios` | 13.6 |
| **Total** | 278.9 |

Maybe we could move the QR code generation server-side, though I think that would also require bandwidth down the road when users download those images. Other than that, I don't see a lot of low-hanging fruit among the dependencies.

I also don't think we're gzipping the CSS or JS. Maybe that'd be worth doing as well?

**Comment by matthew-white** [comment]
@clint-tseng, now that [Central is using gzip](https://github.com/opendatakit/central/pull/15), do you think we're able to close this issue? Once minified and zipped, the CSS is 19KB and the JS is 155KB. I think we should keep our eyes on the JS, as that'll only grow as we add more pages, but maybe these are reasonable sizes for the time being?

**Comment by clint-tseng** [comment]
yeah, that's much closer to an acceptable range. both are still larger than they need to be but we can live with it for now.

**Comment by matthew-white** [comment]
Sounds good. I'll go ahead and close for now, but we can reopen or create a new issue if the CSS or JS starts getting too large.
