### ISSUE TITLE
Style tweaks

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#49]
Style tweaks to consider:

# Navbar

- After clicking the user's email address and hovering over **Log out**, only part of the background is gray.
- Dropdown menus seem slightly misaligned with the edge of the buttons that open them (in navbar and other places).
- After collapsing the navbar and clicking the user's email address, the background color of **Log out** is gray.

# Other

- In buttons, the icon could probably be a few more pixels away from the button text.

**Comment by clint-tseng** [comment]
> Is the background color of tables a gradient?

No, the background of the whole page is a gradient; that's already done.

**Comment by matthew-white** [comment]
> - After clicking the user's email address and hovering over **Log out**, only part of the background is gray.

I'm actually not seeing this behavior anymore.

> - Dropdown menus seem slightly misaligned with the edge of the buttons that open them (in navbar and other places).

Moved to #139.

> - After collapsing the navbar and clicking the user's email address, the background color of **Log out** is gray.

There are probably a few places at this point where styles would need to be adjusted for a smaller viewport, so I think we can tackle this if/when we address those.

> - In buttons, the icon could probably be a few more pixels away from the button text.

Moved to #137.
