### ISSUE TITLE
Move assets to definitive build artifact directory

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#77]
**See #140 for more context and how this issue relates to #76.**

@clint-tseng writes:

> there ought to be some definitive build artifact directory
> where if we snapshot that and dump it somewhere it's the minimal set of files needed to work

We should move `assets/` (at least the fonts) and the built .html file to this directory.

**Comment by matthew-white** [comment]
I'm seeing now that vueify is deprecated. As part of this issue, perhaps we should also move from browserify to webpack/rollup?

**Comment by clint-tseng** [comment]
as i understand it, webpack will make your life miserable.

**Comment by matthew-white** [comment]
I've been happy with browserify so far, but I'm feeling slightly uncomfortable now that [vueify](https://github.com/vuejs/vueify) is deprecated: apparently Vue is prioritizing its support for webpack and Rollup. For both webpack and Rollup, Vue has configs and documentation to help you get started. Rollup seems mostly intended for libraries and plugins, but it seems that it can also be used for web apps. @clint-tseng, have you heard anything positive about Rollup?

**Comment by clint-tseng** [comment]
no, i haven't. i only know that i've only heard horror stories about webpack and its complexity and its build times. somebody once told me, three years into using webpack, "we're finally just beginning to understand how it works"
