### ISSUE TITLE
Add back documentation links

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#91]
Before the first public release of Central, we removed several documentation links: see https://github.com/opendatakit/central-frontend/commit/590be6e81ebe17e7b4411e60653aebb4fb3d0fc9. Now that we have documentation up [here](https://docs.opendatakit.org/central-intro/), we should add back those links, making sure that each points to the correct page of the documentation.

**Comment by lognaturel** [comment]
This is ready! Maybe a little more context would help make it a perfect first issue?

**Comment by matthew-white** [comment]
Just added more details — this should be ready now!
